sudo: required
services:
  - docker

before_install:
  - docker build -t alverta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alverta/react-test npm test

after_success:
  - docker build -t alverta/multi-client ./client
  - docker build -t alverta/multi-nginx ./nginx
  - docker build -t alverta/multi-server ./server
  - docker build -t alverta/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hubs
  - docker push alverta/multi-client
  - docker push alverta/multi-nginx
  - docker push alverta/multi-server
  - docker push alverta/multi-worker
